### ISSUE TITLE
Changing SingleFile settings on iOS

### ISSUE THREAD

**Issue by cpick** [gildas-lormeau/SingleFile-Safari-Extension#1]
Is there a way to edit/change/import SingleFile settings when it's running as a Safari extension on iOS (17.5.1)?

The SingleFile iOS app doesn't seem to provide any access to the extension's settings (either in the app itself or via iOS system Settings) and I don't see any way to access them from Safari via its "aA"/extension button or its "Manage Extensions" screen.

I also haven't had luck enabling "synchronize options" within the SingleFile settings in Safari on macOS. [MDN indicates](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync) that:
> Safari 15 and 15.1 erroneously store sync items in the local storage area. If unable to locate sync items, check for sync items in the local storage area and do a one-time migration to the sync storage area.

I can't tell if that means the settings will be synchronized if that one-time migration is performed?

Ultimately what I'm trying to do is use SinglePage's the "Destination > upload to a REST Form API" option from iOS as well as macOS.

Thanks for such a great extension and please let me know if any more info or testing would be helpful!

**Comment by cpick** [comment]
> I also haven't had luck enabling "synchronize options" within the SingleFile settings in Safari on macOS. [MDN indicates](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync) that:
> 
> > Safari 15 and 15.1 erroneously store sync items in the local storage area. If unable to locate sync items, check for sync items in the local storage area and do a one-time migration to the sync storage area.
> 
> I can't tell if that means the settings will be synchronized if that one-time migration is performed?

[Other sources](https://lapcatsoftware.com/articles/storage.html) seem to indicate that even though Safari 15 had issues conflating `local` and `sync` storage (that were fixed in 15.2) none of those versions ever actually synchronized that storage between devices (via iCloud or similar).  That is: `sync` behaves similarly to `local` and is just another namespace for local storage.

**Comment by gildas-lormeau** [comment]
Thank you for the bug report. I was able to reproduce the issue by using SingleFile in Safari and Safari Technology Preview, and trying to sync the settings between the 2 browsers.

It looks like the synchronisation feature is (still) not supported, see https://developer.apple.com/documentation/safariservices/safari_web_extensions/assessing_your_safari_web_extension_s_browser_compatibility#3584139. Maybe I should disable the sync feature in Safari.

**Comment by gildas-lormeau** [comment]
In order to change the settings of SingleFile on iOS, you have to go first into the settings of Safari. Then, you can access to the settings of your extensions.

**Comment by cpick** [comment]
Thank you for taking the time to have a look and for your help guiding me to the extension settings on iOS which solved my problem!
